# Generated by Django 4.2.7 on 2024-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='slug',
            field=models.SlugField(),
        ),
    ]
